name: docker-build-push

on:
  push:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_ENDPOINT }}/${{ vars.CONTAINER_IMAGE_NAME }}:latest
            ${{ secrets.REGISTRY_ENDPOINT }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
